# Generated by Django 3.2.5 on 2021-07-19 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
